### ISSUE TITLE
Create a simple executable script

### ISSUE THREAD

**Issue by fbiville** [nicokosi/hubstats#6]
If you don't plan on supporting Windows, you could create a simple executable script with this [one weird trick](https://coderwall.com/p/ssuaxa/how-to-make-a-jar-file-linux-executable) (all developers hate him).

**Comment by nicokosi** [comment]
Thanks for the tip, I will give a try!

**Comment by nicokosi** [comment]
@fbiville I have created https://github.com/nicokosi/hubstats/pull/7 in case you want to review/merge it.
